--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/EasyKits
build-by-default: true
branches:
  - PM5
  - master
projects:
  EasyKits:
    path: ""
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
      - src: ACM-PocketMine-MP/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^2.0.0
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6.5
        branch: "pm5"
    lint:
       phpstan: false
...
