--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AndreasHGK/EasyKits
branches:
  - PM5
  - master
projects:
  EasyKits:
    path: ""
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
      - src: ACM-PocketMine-MP/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^2.0.0
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6.1
        branch: "pm5"
...
